pipeline:
  name: train_model
description: "Run the Brain MRI Training Experiment on MLDE"
input:
  pfs:
    glob: "/*[!_report]"
    repo: resize_images
    name: data
    branch: master
    empty_files: true
transform:
  cmd: ["/bin/sh"]
  stdin: ["python train.py --git-url https://git@github.com/denisabrantes/pdk_workshop_brainmri.git --git-ref main --sub-dir experiment --config const.yaml --repo resize_images  --incremental false --workspace YYYY_MM_DD_Workshop --model pdk-brain-mri --mlde_project default --project brain-mri-workshop"]
  image: us-central1-docker.pkg.dev/dai-dev-554/denisd-registry/pdk_ws_brainmri_modeltrain:1.03_reg
  secrets: 
  - name: pipeline-secret
    key: det_master
    env_var: DET_MASTER
  - name: pipeline-secret
    key: det_user
    env_var: DET_USER
  - name: pipeline-secret
    key: det_password
    env_var: DET_PASSWORD
  - name: pipeline-secret
    key: pac_token
    env_var: PAC_TOKEN
  - name: pipeline-secret
    key: mldm_host
    env_var: PACHD_PEER_SERVICE_HOST
  - name: pipeline-secret
    key: mldm_port
    env_var: PACHD_PEER_SERVICE_PORT    
datum_tries: 1
parallelism_spec:
  constant: 1
autoscaling: true
